try :
    raise NameError("hithere")

except NameError:
    print("an exception flew by")
    




    